### ISSUE TITLE
[New Feature] New dev branch

### ISSUE THREAD

**Issue by yassindeb** [ferrariofilippo/woel#19]
**Feature description**
 Add a dev branch and set is as default, leaving the main branch only for releases.

**Solution**
Rename current main branch to dev and create a new clean main branch that will be used only after we start with releases.

**Comment by ferrariofilippo** [comment]
Done. Run the following commands to update your locale clone:
- `git branch -m main dev`
- `git fetch origin`
- `git branch -u origin/dev dev`
- `git remote set-head origin -a`
