### ISSUE TITLE
[Bug] Ad Image Incomplete src URL

### ISSUE THREAD

**Issue by yassindeb** [ferrariofilippo/woel#20]
**Describe the bug**
Error when creating a new ad with an image.
Error: Failed to parse src "1c6bda2a-0607-414f-a31e-f34a608a9335.jpg" on `next/image`, if using relative image it must start with a leading slash "/" or be an absolute URL (http:// or https://)

**To Reproduce**
1. Create an ad
2. Click on the user profile
3. See error

**Expected behavior**
The images should be uploaded to with a correct image path that includes the full path of the image storage bucket url.

**Screenshots**
![image](https://github.com/ferrariofilippo/woel/assets/79911341/6fe68551-8279-42bd-b997-6ab8971faf27)

**Comment by ferrariofilippo** [comment]
I'm not sure we should save the full path: it depends on too many variables (`https://INSTANCE_NAME.supabase.co/storage/VERSION/object/BUCKET_TYPE/BUCKET_NAME`). 
I think we should rather use `supabase.storage.from("BUCKET_NAME").getPublicUrl(SAVED_URL).data.publicUrl` to get images.

**Comment by yassindeb** [comment]
The thing is that the uploaded avatars appear in the db with a src column that contains the full image URL while, the ad pictures don't it's not that big of a deal, we just have to decide whether to have 2 separate approaches or one.
In my opinion it makes sense to have the full url in case we want to migrate to our own database istance in the future.

**Comment by ferrariofilippo** [comment]
> In my opinion it makes sense to have the full url in case we want to migrate to our own database istance in the future.

Actually, in this case it would be better to have the relative paths, otherwise we would need to update all the rows on the new DB.
We might choose to hard-code the first part of the path, instead of retrieving it using the Supabase library, but I still think that the relative URLs would be better

**Comment by yassindeb** [comment]
Yeah you have a point here, alright then we shall do as you did with the ad creation section: using relative paths.
